import { Brand } from "@/types/brand";

const brandsData: Brand[] = [
  {
    id: 1,
    name: "Rest Pinheiros",
    href: null,
    image: "/images/brands/restpinheiros.png",
    imageLight: "/images/brands/restpinheiros.png",
  },
  {
    id: 2,
    name: "Taberna da Carne",
    href: "https://tabernadacarne.com.br",
    image: "/images/brands/tabernadacarne-light.svg",
    imageLight: "/images/brands/tabernadacarne.svg",
  },
  {
    id: 3,
    name: "UFCA",
    href: "https://www.ufca.edu.br",
    image: "/images/brands/ufca-light.png",
    imageLight: "/images/brands/ufca.png",
  },
  {
    id: 4,
    name: "Instituto Federal de Educação, Ciência e Tecnologia do Ceará - Campus Juazeiro do Norte",
    href: "https://ifce.edu.br/juazeirodonorte",
    image: "/images/brands/ifc.svg",
    imageLight: "/images/brands/ifc-dark.svg",
  },
  {
    id: 5,
    name: "URCA",
    href: "https://www.urca.br",
    image: "/images/brands/urca-dark.png",
    imageLight: "/images/brands/urca-light.png",
  },
  {
    id: 6,
    name: "Trevo Drywall",
    href: "https://www.trevodrywall.com.br",
    image: "/images/brands/trevo.svg",
    imageLight: "/images/brands/trevo.svg",
  },
  {
    id: 7,
    name: "AMJUR",
    href: "https://juazeirodonorte.ce.gov.br/secretaria.php?sec=17",
    image: "/images/brands/amaju-light.svg",
    imageLight: "/images/brands/amaju-dark.png",
  },
  {
    id: 8,
    name: "COOKARIRI",
    href: "https://www.instagram.com/redecookariri/",
    image: "/images/brands/cookariri.svg",
    imageLight: "/images/brands/cookariri.svg",
  },
  {
    id: 9,
    name: "FIEC",
    href: "https://www1.sfiec.org.br",
    image: "/images/brands/fiec.png",
    imageLight: "/images/brands/fiec.png",
  },
  {
    id: 10,
    name: "IEL",
    href: "https://www.iel-ce.org.br",
    image: "/images/brands/iel.png",
    imageLight: "/images/brands/iel.png",
  },
  {
    id: 11,
    name: "CTI-AMBIENTAL",
    href: "https://ctiambiental.com.br",
    image: "/images/brands/cti-light.png",
    imageLight: "/images/brands/cti-dark.png",
  },
  {
    id: 12,
    name: "CADAFALSO",
    href: "null",
    image: "/images/brands/cadafalso.jpeg",
    imageLight: "/images/brands/cadafalso.jpeg",
  },
  {
    id: 14,
    name: "STARLIMP",
    href: "https://www.instagram.com/starlimp.me/",
    image: "/images/brands/starlimp.png",
    imageLight: "/images/brands/starlimp.png",
  },

  {
    id: 15,
    name: "WBT",
    href: "null",
    image: "/images/brands/darck_wbt.png",
    imageLight: "/images/brands/lightwbt.png",
  },
  {
    id: 16,
    name: "SEU_CONSTRUTOR",
    href: "null",
    image: "/images/brands/seu_light.png",
    imageLight: "/images/brands/seu_darck.png",
  },
];
export default brandsData;
